package batistaReviver.studentApi.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.util.HashSet;
import java.util.Set;

/**
 * Represents a professor at the institution.
 *
 * This entity is mapped to the "professors" table in the database. It holds personal
 * and contact information for a professor, as well as the classes they teach.
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "professors")
public class Professor {

    /**
     * The unique identifier for the professor.
     * This value is auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The full name of the professor.
     * This field cannot be null.
     */
    @Column(nullable = false)
    private String name;

    /**
     * The phone number of the professor.
     * This field must be unique and cannot be null.
     */
    @Column(nullable = false, unique = true)
    private String phone;

    /**
     * The email address of the professor.
     * This field must be unique and cannot be null.
     */
    @Column(nullable = false, unique = true)
    private String email;

    /**
     * The unique identification number for the professor (e.g., employee ID).
     */
    @Column(unique = true)
    private String idNumber;

    /**
     * The set of classes taught by this professor.
     * Establishes a one-to-many relationship with the StudyClass entity.
     */
    @OneToMany(mappedBy = "professor", cascade = CascadeType.ALL, orphanRemoval = true, fetch = FetchType.LAZY)
    private Set<StudyClass> studyClasses = new HashSet<>();


    /**
     * Constructs a new Professor instance without an ID.
     * This is useful for creating new professor records before they are persisted.
     *
     * @param name The professor's full name.
     * @param phone The professor's phone number.
     * @param email The professor's email address.
     * @param idNumber The professor's identification number.
     */
    public Professor(String name, String phone, String email, String idNumber) {
        this.name = name;
        this.phone = phone;
        this.email = email;
        this.idNumber = idNumber;
    }
}
